[package]
name = "lowell-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
goblin = "0.10"
rs-release = "0.1.11"
sha2 = { version = "0.10", features = ["asm"]}


[dev-dependencies]
tempfile = "3"
